ProsessPilotene.Signicat.WebApi/Controllers/SignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http.Results;
using System.Web.Mvc;
using Microsoft.AspNetCore.Mvc;

namespace PP.Signicat.WebApi.Controllers
{
    public class SignController : Controller
    {
        // GET: Sign
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProsessPilotene.Signicat.WebApi/Views/Shared/SignCallBack.cshtml
<html>
<head>
    <script type="text/javascript" src="ClientGlobalContext.js.aspx"></script>
    <script src="https://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>


    <title>Document Signing</title>
    <meta charset="utf-8">
    <meta>
</head>
<body>

    <div class="container">
        <div class="header clearfix">
            <nav>
                <ul class="nav nav-pills pull-right">
                    <li role="presentation">
                        <a href="https://www.signicat.com/contact_us/" target="_blank">
                            @*<img src="~/Resources/signicat-logo.png" />*@
                            Signicat AS
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="https://prosesspilotene.no/nb/kontakt" target="_blank">
                            @*<img src="~/Resources/prosesspilotene_logo_horizontal.png" />*@
                            ProsessPilotene AS
                        </a>
                    </li>
                </ul>
            </nav>
            <h3 class="text-muted">Signicat for Dynamics365</h3>
        </div>

        <div class="jumbotron">
            <h1>Document Signed</h1>
            <p class="lead">The documents has been signed successfully and sent back to the issuer.</p>
          @*  <p><a class="btn-sm btn-info" href="mailto:support@prosesspilotene.no" role="button" style="float:right">Contact us for support.</a></p>*@
        </div>

        <div class="row marketing">
            <div class="col-lg-6">
                <h4></h4>
                <p></p>

                <h4></h4>
                <p></p>

                <h4></h4>
                <p></p>
            </div>

            <div class="col-lg-6">
                <h4></h4>
                <p></p>

                <h4></h4>
                <p></p>

                <h4></h4>
                <p></p>
            </div>
        </div>

        <footer class="footer">
            <p>© @DateTime.Now.Year Signicat AS & ProsessPilotene AS.</p>
        </footer>

    </div> <!-- /container -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>


</body>
</html>

ProsessPilotene.Signicat.WebApi/Views/Shared/SignCallBackNB.cshtml
<html>
<head>
    <script type="text/javascript" src="ClientGlobalContext.js.aspx"></script>
    <script src="https://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>


    <title>Dokument signering</title>
    <meta charset="utf-8">
    <meta>
</head>
<body>

    <div class="container">
        <div class="header clearfix">
            <nav>
                <ul class="nav nav-pills pull-right">
                    <li role="presentation">
                        <a href="https://www.signicat.com/contact_us/" target="_blank">
                            @*<img src="~/Resources/signicat-logo.png" />*@
                            Signicat AS
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="https://prosesspilotene.no/nb/kontakt" target="_blank">
                            @*<img src="~/Resources/prosesspilotene_logo_horizontal.png" />*@
                            ProsessPilotene AS
                        </a>
                    </li>
                </ul>
            </nav>
            <h3 class="text-muted">Signicat for Dynamics365</h3>
        </div>

        <div class="jumbotron">
            <h1>Dokument(er) er signert</h1>
            <p class="lead">Dokumentene har blitt signert og sendt tilbake til avsender.</p>
            @*  <p><a class="btn-sm btn-info" href="mailto:support@prosesspilotene.no" role="button" style="float:right">Contact us for support.</a></p>*@
        </div>

        <div class="row marketing">
            <div class="col-lg-6">
                <h4></h4>
                <p></p>

                <h4></h4>
                <p></p>

                <h4></h4>
                <p></p>
            </div>

            <div class="col-lg-6">
                <h4></h4>
                <p></p>

                <h4></h4>
                <p></p>

                <h4></h4>
                <p></p>
            </div>
        </div>

        <footer class="footer">
            <p>© @DateTime.Now.Year Signicat AS & ProsessPilotene AS.</p>
        </footer>

    </div> <!-- /container -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>


</body>
</html>

ProsessPilotene.Signicat.WebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Signicat signing", "Index", "Sign", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @*<ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Signering", "Index", "Sign", new { area = "" }, null)</li>
                </ul>*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Prosesspilotene</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/notify")
    @Styles.Render("~/Content/css")
    @RenderSection("scripts", required: false)
</body>
</html>